# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Philip Wong
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my space where I post stuff on the web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pwong.co.uk" # the base hostname & protocol for your site
github_username: p2635

# Build settings
markdown: kramdown
